import { NextRequest, NextResponse } from 'next/server';
import { createGitHubRepo, pushToGitHub } from '@/lib/github';
import { getAdminAuth } from '@/lib/firebase-admin';

export async function POST(req: NextRequest) {
    try {
        const adminAuth = getAdminAuth();
        // 1. Authenticate Request
        const authHeader = req.headers.get('Authorization');
        if (!authHeader?.startsWith('Bearer ')) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
        }
        const idToken = authHeader.split('Bearer ')[1];
        const decodedToken = await adminAuth.verifyIdToken(idToken);
        const userId = decodedToken.uid;

        const { repoName, htmlContent, accessToken } = await req.json();

        // Note: accessToken should ideally be stored securely on server linked to user
        // But for MVP, client might pass it after OAuth flow or we fetch from DB if stored.
        // Let's assume passed for now or we need a robust token store.

        if (!accessToken) {
            return NextResponse.json({ error: 'GitHub Access Token required' }, { status: 400 });
        }

        // 2. Create Repo
        const repoData = await createGitHubRepo(accessToken, repoName, 'Generated by GenApps.online');

        // 3. Push Code
        await pushToGitHub(accessToken, repoData.owner.login, repoName, [
            { path: 'index.html', content: htmlContent },
            { path: 'README.md', content: '# Generated Website\n\nBuilt with [GenApps.online](https://genapps.online)' }
        ], 'Initial commit from GenApps');

        return NextResponse.json({
            success: true,
            repoUrl: repoData.html_url
        });

    } catch (error) {
        console.error('GitHub Integration Error:', error);
        return NextResponse.json(
            { error: error instanceof Error ? error.message : 'GitHub action failed' },
            { status: 500 }
        );
    }
}
